### ISSUE TITLE
ImportError: cannot import name 'psd_welch' from 'mne.time_frequency'

### ISSUE THREAD

**Issue by mmagnuski** [mmagnuski/borsar#111]
New mne does not have `psd_welch`. I'll have to see if new mne Spectrum classes can replace `borsar.freq.PSD`.

**Comment by drammock** [comment]
LMK if you have any questions about switching to Spectrum class.

**Comment by mmagnuski** [comment]
Thanks! My main question so far was if it is possible to create `Spectrum` class when I already have psds, freqs etc. So something like `SpectrumArray`.

**Comment by drammock** [comment]
> Thanks! My main question so far was if it is possible to create `Spectrum` class instance when I already have psds, freqs etc. So something like `SpectrumArray`.

Not yet implemented :(  sorry.

**Comment by drammock** [comment]
actually, you could probably hack it fairly easily though by taking advantage of the `__setstate__` method...  basically if you pass a dict to the `Spectrum` class constructor it will short-circuit the init and just set all the relevant values from that dict.

**Comment by mmagnuski** [comment]
Cool, thanks, I'll try it out!
